### ISSUE TITLE
complete history functions

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#104]
use indexdb instead?

**Comment by frantic0** [comment]
notes:
localStorage doesn't allow objects so there's no way to add items to an array of history iitesm, unless you keep parsing it an unparsing it
which could bring in performance issues

instead: each history item is added as a separate localStorage entry, we'll need to add some utility functions to this class to organise
them an query them.

you can access all the keys in localStorage using Object.entries(localStoage) and then take things from there. Functions we need:

- clear history
- export history to document in date order (in a window) (supercollider style)

**Comment by frantic0** [comment]
done
