### ISSUE TITLE
tutorial loading

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#136]
at the moment, the text for the intro tutorial always loads when switching to the tutorial pane - it should be the text for the previous tutorial.

**Comment by frantic0** [comment]
by previous tutorial do you mean the last selected tutorial? 

like keeping the state of the last selected tutorial between navigations?

**Comment by frantic0** [comment]
I sorted out the maintenance of state but there's a problem with first navigation

Read about it here https://github.com/sveltech/routify/issues/186

**Comment by frantic0** [comment]
fixed
