### ISSUE TITLE
The '>' operator 

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#138]
Maybe I didn't understand the semantics of the '>' operator (where are they?)...

Shouldn't it disappear as default, when all lines of code have it?

Also, why do all lines need it? shouldnt it be used in the last line (the mix to DAC) to denote which output the audio is routed to?

**Comment by chriskiefer** [comment]
i'll write a tutorial on this - it's just the line that you want to output to the DAC, whereever that is
