### ISSUE TITLE
livecode evaluation fails when there's only one line of text in the editor

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#169]
if you enter a single line of code, but don't press [enter] to create a new line, then you can type whatever you want and it always evaluates to an empty tree.

**Comment by frantic0** [comment]
this must be related to this bug, I have introduced some changes to the component algorithm might not have tested all the cases

https://github.com/mimic-sussex/sema/issues/134

**Comment by chriskiefer** [comment]
ok - update on this, it doesn't evaluate the last line of code, unless there's a \n at the end - this includes when there's nore than one line of code
