### ISSUE TITLE
ctrl-. not working on linux

### ISSUE THREAD

**Issue by kflak** [mimic-sussex/sema#171]
Hi guys,

Looking forward to the workshop! 

Been fiddling around a bit with the tutorials, but I can't make the sound go away :-/ I've tried on both chromium and qutebrowser (chromium-based), as well as on wayland (sway) and xorg (i3). Running on Arch Linux 5.6.17-rt10-1-rt. How can I debug? And is there a way to send sound-off as a command instead of a keyboard shortcut?

EDIT: I installed `sema` by running:
```bash
git clone https://github.com/mimic-sussex/sema.git
cd sema
yarn
yarn build
yarn serve
```
Node v14.4.0 if that is of any help...

**Comment by ojack** [comment]
This is happening for me in the browser playground and tutorial as well. Is there any other way to stop the sound in the meantime?

**Comment by frantic0** [comment]
Unfortunately I don't have a linux or window machine to debug that... Let me figure it out.

Meanwhile, you can remove the DAC sinal `>` or set the mix to 0 `> {0}mix;`

**Comment by frantic0** [comment]
ok, the next deployment should have the ctrl-. operational ;)

**Comment by kflak** [comment]
Awesome!
