### ISSUE TITLE
Playground/tutorials break on refresh

### ISSUE THREAD

**Issue by sambilbow** [mimic-sussex/sema#174]
System: macOS Catalina 10.15.2
Browser: Chrome 83.0.4103.116 (Official Build) (64-bit)

### **Page refresh when on Playground results in 404.**
![Screenshot 2020-06-29 at 14 35 01](https://user-images.githubusercontent.com/31018239/86012316-b8755c00-ba15-11ea-8041-225c6bf9dbc0.png)

### **Page refresh when on Tutorial results in page full of markdown.**
![Screenshot 2020-06-29 at 14 35 24](https://user-images.githubusercontent.com/31018239/86012350-c62ae180-ba15-11ea-95e4-58c83bb03676.png)

### **Refreshing on sema.codes fixes this**

**Comment by frantic0** [comment]
live reload should be fixed on this version
