### ISSUE TITLE
Safari not working - https://sema.codes

### ISSUE THREAD

**Issue by suyashjoshi** [mimic-sussex/sema#186]
Sorry, this browser does not work for Sema...

Sema requires a Chromium-based browser as it uses the latest Web Audio API technology

(we recommend Chrome, but also possible are Brave, Microsoft Edge, Opera, Vivaldi)

**Comment by suyashjoshi** [comment]
https://caniuse.com/#search=web%20audio - "-webkit" prefix needs to be used to allow web audio to work on Safari

**Comment by frantic0** [comment]
@suyashjoshi Web Audio API Worklets are not suported by Safari.
