### ISSUE TITLE
integrate reference documentation in the frontend, rendering the markdown content from github in the `docs` page

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#200]
Users will benefit from an integrated experience to the reference documentation in the front end. 

This means navigating from the global navigation bar to a 'docs' page with a layout sidebar/content page, which lists the main documents on the sidebar, which can be selected and have their content rendered on the content page.

However, we want to keep the possibility of users submitting documentation contributions using pull requests. Currently, documentation is published here [https://github.com/mimic-sussex/sema/tree/master/docs](https://github.com/mimic-sussex/sema/tree/master/docs). 

Recently there was a quick experiment that replicates the HTML content in the solution https://github.com/mimic-sussex/sema/tree/v0.7.0/src/pages/docs

The implementation, rather than replicating the HTML content in the solution, should consume the markdown content from Github and use the 'marked' component which is already used for the tutorial (https://github.com/mimic-sussex/sema/blob/v0.7.0/src/pages/tutorial/%5Bchapter%5D/%5Bsection%5D/index.svelte).

Finally, the docs content page should have a white background and be minimal, so that we main assign some styling to a designer.

**Comment by smilo7** [comment]
completed in new version
