### ISSUE TITLE
Docs – clearer separation between sidebar bar, title bar, nav bar; can't copy and paste text or code;  in-text links don't open in new tab

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#210]
- clearer separation between sidebar bar, title bar, nav bar; 
- can't copy and paste text or code;
- in-text links don't open in new tab

**Comment by smilo7** [comment]
1 and 2 done. in text links still don't open in new tab. same problem in tutorial.

**Comment by smilo7** [comment]
links open in new tab added in https://github.com/mimic-sussex/sema/pull/333
