### ISSUE TITLE
Commands – link each command to global help, tutorial and documentation 

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#240]

**Comment by smilo7** [comment]
#338 once docs are completed. we can link commands to documentation as url routes will be unlikely to change.

**Comment by smilo7** [comment]
How would we like this to work with the different language options available?

**Comment by smilo7** [comment]
links to documentation have now been added. I think this is sufficient for now. It would be good to support each language page in the future, but more infrastructure needs to be built up first before that can happen.
