### ISSUE TITLE
[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#265]
the sema-engine stopped working on chrome canary (v91) 

this warning explains it all

engine.js:557 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.

this is critical

**Comment by smilo7** [comment]
I believe you fixed this @frantic0? Re-open if I am wrong.
