### ISSUE TITLE
naming convention for model editor window

### ISSUE THREAD

**Issue by smilo7** [mimic-sussex/sema#286]
I have noticed the naming convention for different components within the system isn't always consistent throughout the tutorial and various parts of the interface. I think it would be a good idea to standardize this to make it easier to understand from the perspective of a new user.

For example the modelEditor window is referred to sometimes as:
Javscript Window
ML window
modelEditor
learner?

I can go through and standardize this to one name but I am wondering what naming convention is best to go by?

**Comment by frantic0** [comment]
I think we should stick to "Javascript" window if we all agree.

Running an ML model in this window is optional. Learner refers to an underlying layer in the engine, wh

This was also pointed to in the user interviews (TB)

**Comment by smilo7** [comment]
duplicate https://github.com/mimic-sussex/sema/issues/217

**Comment by smilo7** [comment]
closing as is duplicate but will reference this issue in older issue
