### ISSUE TITLE
add enable-webgl-in-my-browser section to README for tensorflow.js hardware acceleration

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#287]
this can make the difference between second and minutes in the training process

https://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser

**Comment by smilo7** [comment]
We could this to a new section in the documentation on machine learning? How to load tensorflow.js and enable hardware acceleration etc..

**Comment by frantic0** [comment]
that is a good idea

**Comment by smilo7** [comment]
done in https://github.com/mimic-sussex/sema/pull/328
