### ISSUE TITLE
Update links to samples list in tutorial and reference

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#290]
**Reference**

in the default language reference page   

_Sample playback_
The \operator
Samples are preloaded when the audio engine starts up. A list of samples can be found in https://github.com/mimic-sussex/sema/tree/master/assets/samples

**tutorial** 

sample

\909b is the name of a sample, taken from the list of preloaded samples here: samples. You can also generate samples from the

**Comment by smilo7** [comment]
fixed in https://github.com/mimic-sussex/sema/pull/328
