### ISSUE TITLE
rsq sequence is executed in an incorrect order (first element plays last)

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#292]
If you execute this you'll notice that execution starts with note 33 and plays 62 last

```
:midinote:{{1}clp, [1],[62,33,34,35]}rsq;
:freq:{{2,{{:midinote:,69}sub,12}div}pow,440}mul;
:osc:{:freq:}tri;
:scale2:{:osc:, 200, 1, 0, 0, 1, 0}svf;
```

**Comment by chriskiefer** [comment]
fixed

{1}quantise;
:midinote:{{1}clp, [1],[62,33,34,35]}rsq;
:freq:{{2,{{:midinote:,69}sub,12}div}pow,440}mul;
>:osc:{:freq:}tri;
