### ISSUE TITLE
documentation formatting

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#304]
in the intermediate language documentation, the indentation isn't quite right. in each block the first function is left justtified, but then the following functions are indented.

**Comment by chriskiefer** [comment]
also it would be helpful if the title for documentation pages could be 'Sema Docs' so you know which tab is which in your browser

**Comment by smilo7** [comment]
This issue has been fixed in https://github.com/mimic-sussex/sema/pull/306. It can be closed now i think.
