### ISSUE TITLE
Tutorial - Windows dont have top border or buttons

### ISSUE THREAD

**Issue by smilo7** [mimic-sussex/sema#326]
The windows in the tutorials are very hard to control. The top bar is the same colour as the background (not good) and there is no “x” on the right to close the window.

also unable to resize windows.

**Comment by frantic0** [comment]
Tutorial layouts are not meant to be configurable (drag, close or resize windows)

**Comment by frantic0** [comment]
The top bar can definitely improve, that should be something that the designer will be working on

**Comment by smilo7** [comment]
top bar has a lighter colour now. matching that in the playground.
