### ISSUE TITLE
auth0 login url mismatch

### ISSUE THREAD

**Issue by cosmosim** [mimic-sussex/sema#330]
when trying to go through the login section, the modal throws an error: 

"Callback URL mismatch."

"unauthorized_client: Callback URL mismatch. https://sema.codes is not in the list of allowed callback URLs."

**Comment by frantic0** [comment]
@cosmosim thanks, we're about to fix that with the backend

**Comment by frantic0** [comment]
dropping auth0 authentication for supabase
