### ISSUE TITLE
Backend - Email templates on supabase (eg Magic link email)

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#363]
make this a bit more verbose - mention that it's for sema etc, show the link so people can copy/paste if needed

**Comment by smilo7** [comment]
All email templates have now been updated on supabase.
they now include:
- the sema logo
- a button for the requested action (eg Login via magic link)
- the raw link for copy pasting

It would be good to store these all somewhere for future reference, maybe a repo: sema-sb-email-templates

**Comment by smilo7** [comment]
these have now been stored in a repo
