### ISSUE TITLE
'changes not saved' msg after logging in

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#366]
The tooltip says i don't have permissions to save the sketch, but it's not clear to the user why this is the case.

It says make a copy, but there's no 'copy' button

**Comment by smilo7** [comment]
Were you accessing your own or someone elses project?
Was there a uuid in the url bar? such as https://dev.sema.codes/playground/44b7e669-3962-4712-8789-f14408de78e1

The copy button is actually the link, if you click the link it should create a new playground. It should say in the tooltip.

**Comment by smilo7** [comment]
Made some adjustments in an upcoming PR to make this functionality clearer.

Added a fork button to the settings bar in the playground that users may copy projects.

When hovering over the 'Changes cant be saved' link it highlights the fork button so the user is aware of the functionality. 
![image](https://user-images.githubusercontent.com/2623637/141109582-31855e33-0876-4761-964b-9490b2008b60.png)

They can copy via the link or with the fork button.

**Comment by smilo7** [comment]
added on develop branch. the links are also have updated text for each case (not being logged in or lacking sufficient permissions) instead of a blanket 'Changes will not be saved message'
