### ISSUE TITLE
'new project' button doesn't work

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#367]
the button briefly turns red but nothing happens (signed in with github)

**Comment by smilo7** [comment]
I think this should be fixed now, i have just tested again on my end.
I have added a function trigger to the database when users are added to the auth table, to create a row in public.profiles.

For this to work on your account you can either recreate it or set a username and this will also  create an entry on public profiles.

**Comment by smilo7** [comment]
this is fixed in new version on develop branch. Was due to row in user table in database not being created on signup. function trigger in db has now been added.
