### ISSUE TITLE
share link not working

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#370]
it give a generic URL https://dev.sema.codes/playground/

**Comment by smilo7** [comment]
Was there a uuid param in the url bar at the time? eg https://dev.sema.codes/playground/a7f6143b-494b-4ae4-9e27-5c44710efea7

**Comment by smilo7** [comment]
unable to replicate this. i am pretty sure the issue was to do with a user profile not being created in the database. share is working consistently on the new version on dev branch so closing for now.
