### ISSUE TITLE
project saving in zips

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#371]
the processes of downloading and unzipping is quite complicated. Why don't we simplify this and just download the .json file?  The grammar and code txt files are useful but maybe overcomplicating the process - users can just copy and paste from the loaded file if needed.

**Comment by smilo7** [comment]
I agree. Will try adding this.

**Comment by smilo7** [comment]
Added in upcoming PR. File format saves as "playground name - timeanddate.json"
if playground doesn't have a name (ie user might not be logged in) simply saves as playground -timeanddate.json

**Comment by smilo7** [comment]
added on develop branch.
