### ISSUE TITLE
New project, but couldn't open live code parse output window

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#381]
to recreate:

1. make project with livecode + parser output open
2. new project
3. add livecode
4. tried to add parser output but the menu option was grayed out

after a page refresh the option appeared again

**Comment by smilo7** [comment]
just checked this out. seems to only be reproducible for me on chromium, firefox works as expected.
what browser were you using?

**Comment by chriskiefer** [comment]
it was chrome

**Comment by smilo7** [comment]
this seems like it is fixed in the new version. I can no longer reproduce in firefox or chrome. Reopen if it is still an issue for you.
