### ISSUE TITLE
grammar editor: decide how to deal with 'require moo' error

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#66]
this is an item from raw .ne scripts that creates an error in sema. Should we search for this line and automatically ignore it?  otherwise might be confusing to users to deal with this error

**Comment by frantic0** [comment]
If you are talking about these lines 

`var semaIR = require('./semaIR.js'); // load additional sound engine functions
const moo = require("moo"); // load tokeniser`

That is for nearley running server-side, not client-side, as in our case. As such, they cannot exist in our grammar specification and they must be removed from any .ne script.

If you're not talking about those lines please specify
