### ISSUE TITLE
all editors: text search function

### ISSUE THREAD

**Issue by chriskiefer** [mimic-sussex/sema#68]

**Comment by frantic0** [comment]
Integrating support for CodeMirror Addon 

`import 'codemirror/addon/search/search.js';
import 'codemirror/addon/search/searchcursor.js';
import 'codemirror/addon/search/jump-to-line.js';`

Keybinds: 

Ctrl-F / Cmd-F | Start searching
Ctrl-G / Cmd-G / Shift-F3 | Find next
Shift-Ctrl-G / Shift-Cmd-G / F3 | Find previous
Shift-Ctrl-F / Cmd-Option-F | Replace
Shift-Ctrl-R / Shift-Cmd-Option-F | Replace all
Alt-F | Persistent search (dialog doesn't autoclose, enter to find next, Shift-Enter to find previous)
Alt-G | Jump to line
