### ISSUE TITLE
change behaviour of keyboard command shortcuts for stopping/restarting audio

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#80]
as required by the expert live coder at mimic sema session

**Comment by frantic0** [comment]
cmd-. stops audio, cmd-enter evaluates and resumes audio if it was stopped

**Comment by dash1291** [comment]
@frantic0 I see that when cmd-enter never resumes audio once I stop it with cmd-. . Is it fixed somewhere or I'm missing something else? I'm on latest master.

**Comment by frantic0** [comment]
hi @dash1291! 

on branch sema_v0.3 (will merge to master later this week), 'cmd-.' stops audio and 'cmd-enter' resumes.

some Windows OS users reported issues though... Is that your case?

**Comment by dash1291** [comment]
No, I'm on Mac and `sema_v0.3` works flawlessly. And it looks great!
