### ISSUE TITLE
Eval is accumulating PostMsgTransducer per to-fromJS instruction/eval

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#83]
Each time an eval command is issued in a live code editor with toJS/fromJS instructions, 1 PostMsgTransducer is created per each of those instructions.

Not sure if this is intended it seems to be adding garbage to GC, need to look into it w @chriskiefer

**Comment by chriskiefer** [comment]
we need to have new transducers per-eval, but we could do this from an object pool instead, or make sure they are set to null in the tidy up
